name: "Shopify Preview Axe A11y Report"
description: "Run axe accessibility tests on Shopify preview URLs from PR description and comment results."

inputs:
  default_url:
    description: "Fallback URL if no preview found in PR"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    - name: Install dependencies
      shell: bash
      run: |
        npm install -g @axe-core/cli

    - name: Run accessibility checks
      shell: bash
      run: node "${{ github.action_path }}/scripts/run-axe-tests.js"
      env:
        GITHUB_EVENT_NAME: "${{ github.event_name }}"
        PR_BODY: "${{ github.event.pull_request.body }}"
        DEFAULT_URL: "${{ inputs.default_url }}"

    - name: Generate PR comment markdown
      shell: bash
      run: node "${{ github.action_path }}/scripts/generate-axe-comment.js"

    - name: Comment on PR with results
      if: ${{ github.event.pull_request.state == 'open' }}
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const commentBody = fs.readFileSync('axe-comment.md', 'utf8');

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: commentBody,
          });
