name: Test Action

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  test-preview-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run custom AXE preview action
        uses: ./
        with:
          default_url: "https://leafery.ca"
