name: Test BrowserStack Shopify Preview Action

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test-preview-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run custom AXE preview action
        uses: ./
        with:
          preview_url_contains: "shopifypreview.com"
          github_token: ${{ secrets.GITHUB_TOKEN }}
